#UFI cmd
UFI_OP_TEST_UNIT_READY = 0x00
UFI_OP_REQUEST_SENSE = 0x03
UFI_OP_INQUIRY = 0x12
UFI_OP_READ_FORMAT_CAPACITY = 0x23
UFI_OP_READ_CAPACITY = 0x25
UFI_OP_READ_10 = 0x28
UFI_OP_WRITE_10 = 0x2A

#SCSI cmd
SCSI_OP_SAT12 = 0xA1

SCSI_IOCTL_DATA_IN = 1
SCSI_IOCTL_DATA_OUT = 0
SCSI_IOCTL_NON_DATA = SCSI_IOCTL_DATA_OUT


BYTE_PER_SECTOR = 512