
NVME_ZONE_ACTION_RSD = 0x00
NVME_ZONE_ACTION_CLOSE = 0x01
NVME_ZONE_ACTION_FINISH = 0x02
NVME_ZONE_ACTION_OPEN = 0x03
NVME_ZONE_ACTION_RESET = 0x04
NVME_ZONE_ACTION_OFFLINE = 0x05
NVME_ZONE_ACTION_READONLY = 0x06 
NVME_ZONE_ACTION_EMPTY = 0x07
NVME_ZONE_ACTION_SET_ZD_EXT = 0x10

NVME_ZONE_STATE_RESERVED = 0x00
NVME_ZONE_STATE_EMPTY = 0x10
NVME_ZONE_STATE_IMPLICITLY_OPEN = 0x20
NVME_ZONE_STATE_EXPLICITLY_OPEN = 0x30
NVME_ZONE_STATE_CLOSED = 0x40
NVME_ZONE_STATE_READ_ONLY = 0xd0
NVME_ZONE_STATE_FULL = 0xe0
NVME_ZONE_STATE_OFFLINE = 0xf0